// See LICENSE for copyright and license details
// vim: set ft=asciidoc:
SRANDRD(1)
==========
:doctype: manpage

== NAME

srandrd - simple randr daemon

== SYNOPSIS

*srandrd* ['OPTIONS'] 'COMMAND|list'

*list*::
	List outputs and EDIDs and terminate

== OPTIONS

*-h*::
	Print help and exit
*-n*::
	Don't fork to background
*-V*::
    Show version information and exit
*-v*::
    Verbose output
*-e*::
    Emit connected devices at startup

== DESCRIPTION

srandrd(1) is a tool that executes a command on xrandr output change
events, i.e. if a monitor is plugged or unplugged. By default srandrd forks to
background and exits if the xserver exits.
In the childs environment the environment variable 'SRANDRD_ACTION' is set which
is of the format

----
DISPLAYNAME [connected|disconnected|unknown]
----

Furthermore, the environment variable 'SRANDRD_EDID' is set (if available) which
is of the format

----
VENDOR[4]PRODUCT[4]SERIAL[8]
----

Finally, the environment variable 'SRANDRD_SCREENID' is set (if available) which
is of the format

----
XINERAMA_SCREENID[1|2]
----

== EXAMPLE

An example usage could be

----
srandrd display_handler
----

where display_handler being the following script

----
#!/bin/sh

case "$SRANDRD_ACTION" in
  "DVI-0 connected") xrandr --output DVI-0 --auto --right-of LVDS;;
  "VGA-0 connected") xrandr --output VGA-0 --auto --left-of LVDS;;
esac
----

== RESOURCES

github: https://github.com/jceb/srandrd

== RELATED

screenconfig: https://github.com/jceb/screenconfig

== AUTHOR

* Jan Christoph Ebersbach <jceb@e-jc.de>
* Stefan Bolte <portix@gmx.net>
