'\" t
.\"     Title: srandrd
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.4
.\"      Date: 2016-06-05
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SRANDRD" "1" "2016-06-05" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
srandrd \- simple randr daemon
.SH "SYNOPSIS"
.sp
\fBsrandrd\fP [\fIOPTIONS\fP] \fICOMMAND\fP
.SH "OPTIONS"
.sp
\fB\-h\fP
.RS 4
Print help and exit
.RE
.sp
\fB\-n\fP
.RS 4
Don\(cqt fork to background
.RE
.sp
\fB\-V\fP
.RS 4
Show version information and exit
.RE
.sp
\fB\-v\fP
.RS 4
Verbose output
.RE
.SH "DESCRIPTION"
.sp
srandrd(1) is a tool that executes a command on xrandr output change
events, i.e. if a monitor is plugged or unplugged. By default srandrd forks to
background and exits if the xserver exits.
In the childs environment the environment variable \fISRANDRD_ACTION\fP is set which
is of the format
.sp
.if n \{\
.RS 4
.\}
.nf
DISPLAYNAME [connected|disconnected|unknown]
.fi
.if n \{\
.RE
.\}
.sp
Furthermore, the environment variable \fISRANDRD_EDID\fP is set (if available) which
is of the format
.sp
.if n \{\
.RS 4
.\}
.nf
VENDOR[4]PRODUCT[4]SERIAL[8]
.fi
.if n \{\
.RE
.\}
.SH "EXAMPLE"
.sp
An example usage could be
.sp
.if n \{\
.RS 4
.\}
.nf
srandrd display_handler
.fi
.if n \{\
.RE
.\}
.sp
where display_handler being the following script
.sp
.if n \{\
.RS 4
.\}
.nf
#!/bin/sh

case "$SRANDRD_ACTION" in
  "DVI\-0 connected") xrandr \-\-output DVI\-0 \-\-auto \-\-right\-of LVDS;;
  "VGA\-0 connected") xrandr \-\-output VGA\-0 \-\-auto \-\-left\-of LVDS;;
esac
.fi
.if n \{\
.RE
.\}
.SH "RESOURCES"
.sp
github: \c
.URL "https://github.com/jceb/srandrd" "" ""
.SH "AUTHOR"
.sp
Jan Christoph Ebersbach <\c
.MTO "jceb\(ate\-jc.de" "jceb@e\-jc.de" ">"
Stefan Bolte <\c
.MTO "portix\(atgmx.net" "portix@gmx.net" ">"