'\" t
.\"     Title: srandrd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/24/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SRANDRD" "1" "04/24/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
srandrd \- simple randr daemon
.SH "SYNOPSIS"
.sp
\fBsrandrd\fR [\fIOPTIONS\fR] \fICOMMAND\fR
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Print help and exit
.RE
.PP
\fB\-n\fR
.RS 4
Don\(cqt fork to background
.RE
.PP
\fB\-V\fR
.RS 4
Show version information and exit
.RE
.SH "DESCRIPTION"
.sp
srandrd(1) is a tool that executes a command on xrandr output change events, i\&.e\&. if a monitor is plugged or unplugged\&. By default srandrd forks to background and exits if the xserver exits\&. In the childs environment the environment variable \fISRANDRD_ACTION\fR is set which is of the format
.sp
.if n \{\
.RS 4
.\}
.nf
DISPLAYNAME [connected|disconnected|unknown]
.fi
.if n \{\
.RE
.\}
.SH "EXAMPLE"
.sp
An example usage could be
.sp
.if n \{\
.RS 4
.\}
.nf
srandrd display_handler
.fi
.if n \{\
.RE
.\}
.sp
where display_handler being the following script
.sp
.if n \{\
.RS 4
.\}
.nf
#!/bin/sh

case "$SRANDRD_ACTION" in
  "DVI\-0 connected") xrandr \-\-output DVI\-0 \-\-auto \-\-right\-of LVDS;;
  "VGA\-0 connected") xrandr \-\-output VGA\-0 \-\-auto \-\-left\-of LVDS;;
esac
.fi
.if n \{\
.RE
.\}
.SH "RESOURCES"
.sp
bitbucket: http://bitbucket\&.org/portix/srandrd
.SH "AUTHOR"
.sp
Stefan Bolte <portix@gmx\&.net>
